### ISSUE TITLE
Codec configuration?

### ISSUE THREAD

**Issue by trinidadg** [CircusMonkey/ros_rtsp#5]
Hi! first of all, thanks for the great work!

I'm taking the stream form a ROS topic and trying to stream to an android device. 
When using VLC, I am able to see the video, but Android is unable to display it. After some research, I think it is because Android does not support the used codec ( [Android suported formats  ](https://developer.android.com/guide/topics/media/media-formats#video-codecs) )

Is there any way to chenge the one used to one of the ones supported?
The android app is able to play other streams (such as rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov) so that could not be the problem.

Thank you in advance!

**Comment by CircusMonkey** [comment]
Almost any system should be able to decode and play h264 video. There's a bit more investigation to be done into this and its been a while since I've touched this code. There might be an incompatible setting somewhere.

How are you playing the stream on Android? Are you using the gst-android package?

**Comment by CircusMonkey** [comment]
@trinidadg how did you go with this? A lot of time has passed, but I've setup again and have no problem playing the video through the Android VLC app (other than about 3s of lag).
